/* generated with ChatGPT

Prompt: Generate an array of 30 objects that represent a fictitious creative design agency's important documents related to onboarding designers, developers, and project managers. The format of the objects should include the following keys: id, last_updated, doc_url, doc_title, and related_role. Generate this array in Javascript syntax.
 
*/

export const ONBOARDING_DOCS = [
  {
    id: 1,
    last_updated: "2024-08-01",
    doc_url: "https://agency.com/docs/designer-onboarding",
    related_role: "Designer",
    doc_title: "Designer Onboarding Guide",
  },
  {
    id: 2,
    last_updated: "2024-08-05",
    doc_url: "https://agency.com/docs/developer-onboarding",
    related_role: "Developer",
    doc_title: "Developer Onboarding Guide",
  },
  {
    id: 3,
    last_updated: "2024-08-07",
    doc_url: "https://agency.com/docs/pm-onboarding",
    related_role: "Project Manager",
    doc_title: "Project Manager Onboarding Guide",
  },
  {
    id: 4,
    last_updated: "2024-08-10",
    doc_url: "https://agency.com/docs/ui-ux-guidelines",
    related_role: "Designer",
    doc_title: "UI/UX Guidelines",
  },
  {
    id: 5,
    last_updated: "2024-08-12",
    doc_url: "https://agency.com/docs/code-standards",
    related_role: "Developer",
    doc_title: "Code Standards and Best Practices",
  },
  {
    id: 6,
    last_updated: "2024-08-14",
    doc_url: "https://agency.com/docs/agile-workflow",
    related_role: "Project Manager",
    doc_title: "Agile Workflow Overview",
  },
  {
    id: 7,
    last_updated: "2024-08-16",
    doc_url: "https://agency.com/docs/design-toolkit",
    related_role: "Designer",
    doc_title: "Design Toolkit Overview",
  },
  {
    id: 8,
    last_updated: "2024-08-18",
    doc_url: "https://agency.com/docs/api-integration",
    related_role: "Developer",
    doc_title: "API Integration Guide",
  },
  {
    id: 9,
    last_updated: "2024-08-20",
    doc_url: "https://agency.com/docs/sprint-planning",
    related_role: "Project Manager",
    doc_title: "Sprint Planning and Execution",
  },
  {
    id: 10,
    last_updated: "2024-08-22",
    doc_url: "https://agency.com/docs/typography-guidelines",
    related_role: "Designer",
    doc_title: "Typography Guidelines",
  },
  {
    id: 11,
    last_updated: "2024-08-24",
    doc_url: "https://agency.com/docs/version-control",
    related_role: "Developer",
    doc_title: "Version Control Best Practices",
  },
  {
    id: 12,
    last_updated: "2024-08-26",
    doc_url: "https://agency.com/docs/resource-allocation",
    related_role: "Project Manager",
    doc_title: "Resource Allocation Strategy",
  },
  {
    id: 13,
    last_updated: "2024-08-28",
    doc_url: "https://agency.com/docs/prototyping-workflow",
    related_role: "Designer",
    doc_title: "Prototyping Workflow Guide",
  },
  {
    id: 14,
    last_updated: "2024-08-30",
    doc_url: "https://agency.com/docs/performance-optimization",
    related_role: "Developer",
    doc_title: "Performance Optimization Techniques",
  },
  {
    id: 15,
    last_updated: "2024-09-01",
    doc_url: "https://agency.com/docs/stakeholder-management",
    related_role: "Project Manager",
    doc_title: "Stakeholder Management Guide",
  },
  {
    id: 16,
    last_updated: "2024-09-02",
    doc_url: "https://agency.com/docs/brand-guidelines",
    related_role: "Designer",
    doc_title: "Brand Guidelines",
  },
  {
    id: 17,
    last_updated: "2024-09-03",
    doc_url: "https://agency.com/docs/security-protocols",
    related_role: "Developer",
    doc_title: "Security Protocols and Procedures",
  },
  {
    id: 18,
    last_updated: "2024-09-04",
    doc_url: "https://agency.com/docs/project-scope-definition",
    related_role: "Project Manager",
    doc_title: "Project Scope Definition",
  },
  {
    id: 19,
    last_updated: "2024-09-05",
    doc_url: "https://agency.com/docs/design-review-process",
    related_role: "Designer",
    doc_title: "Design Review Process",
  },
  {
    id: 20,
    last_updated: "2024-09-06",
    doc_url: "https://agency.com/docs/testing-deployment",
    related_role: "Developer",
    doc_title: "Testing and Deployment Checklist",
  },
  {
    id: 21,
    last_updated: "2024-09-07",
    doc_url: "https://agency.com/docs/risk-management",
    related_role: "Project Manager",
    doc_title: "Risk Management Strategy",
  },
  {
    id: 22,
    last_updated: "2024-09-08",
    doc_url: "https://agency.com/docs/color-theory-basics",
    related_role: "Designer",
    doc_title: "Color Theory Basics",
  },
  {
    id: 23,
    last_updated: "2024-09-09",
    doc_url: "https://agency.com/docs/cloud-deployment",
    related_role: "Developer",
    doc_title: "Cloud Deployment Guide",
  },
  {
    id: 24,
    last_updated: "2024-09-10",
    doc_url: "https://agency.com/docs/time-tracking",
    related_role: "Project Manager",
    doc_title: "Time Tracking and Reporting",
  },
  {
    id: 25,
    last_updated: "2024-09-11",
    doc_url: "https://agency.com/docs/logo-guidelines",
    related_role: "Designer",
    doc_title: "Logo Usage Guidelines",
  },
  {
    id: 26,
    last_updated: "2024-09-12",
    doc_url: "https://agency.com/docs/database-management",
    related_role: "Developer",
    doc_title: "Database Management Best Practices",
  },
  {
    id: 27,
    last_updated: "2024-09-13",
    doc_url: "https://agency.com/docs/client-communication",
    related_role: "Project Manager",
    doc_title: "Client Communication Guide",
  },
  {
    id: 28,
    last_updated: "2024-09-14",
    doc_url: "https://agency.com/docs/animation-guidelines",
    related_role: "Designer",
    doc_title: "Animation Guidelines",
  },
  {
    id: 29,
    last_updated: "2024-09-15",
    doc_url: "https://agency.com/docs/data-backup-strategies",
    related_role: "Developer",
    doc_title: "Data Backup Strategies",
  },
  {
    id: 30,
    last_updated: "2024-09-16",
    doc_url: "https://agency.com/docs/task-delegation",
    related_role: "Project Manager",
    doc_title: "Task Delegation Techniques",
  },
];
