/* generated with ChatGPT

Prompt: Generate an array of 15 objects that represent a fictitious creative design agency's staff that includes at least one designer, developer, project manager, tech director, marketing director, and VP of strategy. The format of the objects should include the following keys: id, full_name, last_updated, role, expertise, and projects. The full_name value should include a first and last name that is gender neutral. The data type for expertise should be an array of strings that include lower case descriptors of each person's expertise or special skills. Include between 3 and 5 kebab case descriptors for each person's expertise value. The projects key should be an array of project titles that represent projects that person has worked on. Ensure there is overlap between projects to show multiple people have worked on each project. Include 3 to 5 projects for each projects value array. Generate this array of objects in Javascript syntax.
 
*/
const agencyStaff = [
  {
    id: 1,
    full_name: "Alex Morgan",
    last_updated: "2024-08-01",
    role: "designer",
    expertise: ["ui design", "branding", "typography"],
    projects: [
      "brand revamp",
      "landing page redesign",
      "ecommerce rebrand",
      "app ui overhaul",
      "mobile first design",
    ],
  },
  {
    id: 2,
    full_name: "Jordan Taylor",
    last_updated: "2024-08-03",
    role: "developer",
    expertise: [
      "full stack development",
      "api integration",
      "performance optimization",
      "react",
      "node.js",
    ],
    projects: [
      "ecommerce rebrand",
      "app ui overhaul",
      "internal dashboard",
      "website migration",
      "landing page redesign",
    ],
  },
  {
    id: 3,
    full_name: "Morgan Quinn",
    last_updated: "2024-08-05",
    role: "project manager",
    expertise: [
      "agile methodologies",
      "resource management",
      "client communication",
      "sprint planning",
    ],
    projects: [
      "internal dashboard",
      "mobile first design",
      "social media campaign",
      "landing page redesign",
      "ecommerce rebrand",
    ],
  },
  {
    id: 4,
    full_name: "Casey Avery",
    last_updated: "2024-08-07",
    role: "tech director",
    expertise: [
      "software architecture",
      "cloud computing",
      "security strategies",
      "scaling applications",
    ],
    projects: [
      "website migration",
      "cloud integration",
      "internal dashboard",
      "security enhancements",
      "app ui overhaul",
    ],
  },
  {
    id: 5,
    full_name: "Taylor Emerson",
    last_updated: "2024-08-09",
    role: "marketing director",
    expertise: [
      "content strategy",
      "seo",
      "digital campaigns",
      "audience growth",
    ],
    projects: [
      "social media campaign",
      "content refresh",
      "ecommerce rebrand",
      "product launch",
      "email marketing automation",
    ],
  },
  {
    id: 6,
    full_name: "River Finley",
    last_updated: "2024-08-11",
    role: "vp of strategy",
    expertise: [
      "business strategy",
      "market analysis",
      "growth hacking",
      "stakeholder management",
    ],
    projects: [
      "brand revamp",
      "market expansion",
      "content refresh",
      "social media campaign",
      "cloud integration",
    ],
  },
  {
    id: 7,
    full_name: "Skyler Parker",
    last_updated: "2024-08-13",
    role: "designer",
    expertise: ["visual design", "illustration", "motion graphics"],
    projects: [
      "app ui overhaul",
      "brand revamp",
      "animation refresh",
      "ecommerce rebrand",
      "landing page redesign",
    ],
  },
  {
    id: 8,
    full_name: "Reese Jordan",
    last_updated: "2024-08-15",
    role: "developer",
    expertise: [
      "front end development",
      "responsive design",
      "javascript",
      "css animations",
    ],
    projects: [
      "app ui overhaul",
      "internal dashboard",
      "mobile first design",
      "ecommerce rebrand",
      "animation refresh",
    ],
  },
  {
    id: 9,
    full_name: "Quinn Morgan",
    last_updated: "2024-08-17",
    role: "project manager",
    expertise: [
      "team leadership",
      "risk management",
      "time tracking",
      "client onboarding",
    ],
    projects: [
      "website migration",
      "cloud integration",
      "ecommerce rebrand",
      "social media campaign",
      "product launch",
    ],
  },
  {
    id: 10,
    full_name: "Avery Casey",
    last_updated: "2024-08-19",
    role: "tech director",
    expertise: [
      "devops",
      "infrastructure automation",
      "cloud security",
      "continuous integration",
    ],
    projects: [
      "internal dashboard",
      "cloud integration",
      "security enhancements",
      "website migration",
      "app ui overhaul",
    ],
  },
  {
    id: 11,
    full_name: "Ellis Taylor",
    last_updated: "2024-08-21",
    role: "marketing director",
    expertise: [
      "brand strategy",
      "paid media",
      "social media marketing",
      "copywriting",
    ],
    projects: [
      "social media campaign",
      "brand revamp",
      "email marketing automation",
      "ecommerce rebrand",
      "product launch",
    ],
  },
  {
    id: 12,
    full_name: "Riley Skyler",
    last_updated: "2024-08-23",
    role: "vp of strategy",
    expertise: [
      "corporate communications",
      "strategic initiatives",
      "data driven decision making",
      "innovation",
    ],
    projects: [
      "market expansion",
      "brand revamp",
      "product launch",
      "cloud integration",
      "ecommerce rebrand",
    ],
  },
  {
    id: 13,
    full_name: "Emerson Alex",
    last_updated: "2024-08-25",
    role: "designer",
    expertise: [
      "interaction design",
      "wireframing",
      "user research",
      "prototyping",
    ],
    projects: [
      "mobile first design",
      "ecommerce rebrand",
      "internal dashboard",
      "app ui overhaul",
      "landing page redesign",
    ],
  },
  {
    id: 14,
    full_name: "Parker River",
    last_updated: "2024-08-27",
    role: "developer",
    expertise: [
      "back end development",
      "database management",
      "node.js",
      "graphql",
    ],
    projects: [
      "internal dashboard",
      "website migration",
      "cloud integration",
      "app ui overhaul",
      "security enhancements",
    ],
  },
  {
    id: 15,
    full_name: "Finley Reese",
    last_updated: "2024-08-29",
    role: "project manager",
    expertise: [
      "budget management",
      "stakeholder engagement",
      "project scope definition",
      "timeline management",
    ],
    projects: [
      "brand revamp",
      "product launch",
      "ecommerce rebrand",
      "social media campaign",
      "cloud integration",
    ],
  },
];
